-- 1. TIPOS PERSONALIZADOS
CREATE TYPE estado_expo AS ENUM ('ABIERTA', 'CERRADA');

-- 2. ROLES
CREATE TABLE roles
(
    id_rol smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(30) NOT NULL,
    CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

INSERT INTO roles (nombre) VALUES ('ADMIN'), ('ALUMNO');

-- 3. MATERIAS
CREATE TABLE materias
(
    id_materia     int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave_materia  varchar(20)  NOT NULL,
    nombre_materia varchar(100) NOT NULL,
    activo         boolean      NOT NULL DEFAULT true,
    fecha_creacion timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_clave_materia UNIQUE (clave_materia)
);

-- 4. GRUPOS
CREATE TABLE grupos
(
    id_grupo     int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_grupo varchar(100) NOT NULL,
    activo       boolean      NOT NULL DEFAULT true
);

-- 5. MATERIA_GRUPO
CREATE TABLE materia_grupo
(
    id_materia int NOT NULL,
    id_grupo   int NOT NULL,
    PRIMARY KEY (id_materia, id_grupo),
    CONSTRAINT fk_mg_materia FOREIGN KEY (id_materia) 
        REFERENCES materias (id_materia) ON DELETE CASCADE,
    CONSTRAINT fk_mg_grupo FOREIGN KEY (id_grupo) 
        REFERENCES grupos (id_grupo) ON DELETE CASCADE
);

-- 6. USUARIOS
CREATE TABLE usuarios
(
    id_usuario     int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       varchar(50)  NOT NULL,
    email          varchar(150) NOT NULL,
    nombre         varchar(100) NOT NULL DEFAULT '',
    password       varchar(255) NOT NULL,
    id_rol         smallint     NOT NULL,
    activo         boolean      NOT NULL DEFAULT true,
    fecha_creacion timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_username UNIQUE (username),
    CONSTRAINT uq_email    UNIQUE (email),
    CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES roles (id_rol)
);

-- 7. RUBRICAS Y CRITERIOS
CREATE TABLE rubricas
(
    id_rubrica     int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         varchar(100) NOT NULL,
    descripcion    text         NULL,
    publicada      boolean      NOT NULL DEFAULT false,
    fecha_creacion timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE criterios
(
    id_criterio int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rubrica  int          NOT NULL,
    descripcion varchar(255) NOT NULL,
    ponderacion decimal(5,2) NOT NULL,
    escala_min  decimal(5,2) NOT NULL DEFAULT 0.00,
    escala_max  decimal(5,2) NOT NULL DEFAULT 10.00,
    CONSTRAINT fk_criterio_rubrica FOREIGN KEY (id_rubrica) 
        REFERENCES rubricas (id_rubrica) ON DELETE CASCADE,
    CONSTRAINT chk_ponderacion CHECK (ponderacion > 0),
    CONSTRAINT chk_escala      CHECK (escala_min < escala_max)
);

-- 8. EQUIPOS (Relacionados a un grupo específico)
CREATE TABLE equipos
(
    id_equipo      int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_equipo  varchar(100) NOT NULL,
    id_grupo       int          NOT NULL,
    id_jefe        int          NULL,
    activo         boolean      NOT NULL DEFAULT true,
    fecha_creacion timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_equipo_grupo UNIQUE (nombre_equipo, id_grupo),
    CONSTRAINT fk_equipo_grupo FOREIGN KEY (id_grupo) 
        REFERENCES grupos (id_grupo) ON DELETE CASCADE,
    CONSTRAINT fk_equipo_jefe  FOREIGN KEY (id_jefe) 
        REFERENCES usuarios (id_usuario)
);

-- 9. EQUIPO_ALUMNO (Membresía)
CREATE TABLE equipo_alumno
(
    id_equipo   int       NOT NULL,
    id_alumno   int       NOT NULL,
    fecha_union timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_equipo, id_alumno),
    CONSTRAINT fk_ea_equipo FOREIGN KEY (id_equipo) 
        REFERENCES equipos (id_equipo) ON DELETE CASCADE,
    CONSTRAINT fk_ea_alumno FOREIGN KEY (id_alumno) 
        REFERENCES usuarios (id_usuario) ON DELETE CASCADE
);

-- 10. EXPOSICIONES
CREATE TABLE exposiciones
(
    id_exposicion  int          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo         varchar(150) NOT NULL,
    descripcion    text         NULL,
    estado         estado_expo  NOT NULL DEFAULT 'ABIERTA',
    id_equipo      int          NOT NULL,
    id_rubrica     int          NOT NULL,
    fecha_inicio   date         NOT NULL,
    fecha_fin      date         NOT NULL,
    fecha_creacion timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_fechas      CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT fk_expo_equipo  FOREIGN KEY (id_equipo) 
        REFERENCES equipos (id_equipo) ON DELETE CASCADE,
    CONSTRAINT fk_expo_rubrica FOREIGN KEY (id_rubrica) 
        REFERENCES rubricas (id_rubrica)
);

-- 11. EVALUACIONES
CREATE TABLE evaluaciones
(
    id_evaluacion       bigint    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_exposicion       int       NOT NULL,
    id_alumno_evaluador int       NOT NULL,
    fecha_evaluacion    timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_eval_expo_evaluador UNIQUE (id_exposicion, id_alumno_evaluador),
    CONSTRAINT fk_eval_exposicion FOREIGN KEY (id_exposicion) 
        REFERENCES exposiciones (id_exposicion) ON DELETE CASCADE,
    CONSTRAINT fk_eval_evaluador  FOREIGN KEY (id_alumno_evaluador) 
        REFERENCES usuarios (id_usuario) ON DELETE CASCADE
);

-- 12. DETALLE_EVALUACION
CREATE TABLE detalle_evaluacion
(
    id_detalle    bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evaluacion bigint       NOT NULL,
    id_criterio   int          NOT NULL,
    calificacion  decimal(5,2) NOT NULL,
    CONSTRAINT uq_detalle_eval_criterio UNIQUE (id_evaluacion, id_criterio),
    CONSTRAINT fk_detalle_eval     FOREIGN KEY (id_evaluacion) 
        REFERENCES evaluaciones (id_evaluacion) ON DELETE CASCADE,
    CONSTRAINT fk_detalle_criterio FOREIGN KEY (id_criterio) 
        REFERENCES criterios (id_criterio),
    CONSTRAINT chk_calificacion CHECK (calificacion >= 0 AND calificacion <= 10)
);

-- ÍNDICES PARA OPTIMIZACIÓN
CREATE INDEX idx_materia_nombre ON materias (nombre_materia);
CREATE INDEX idx_usuario_rol    ON usuarios (id_rol);
CREATE INDEX idx_equipo_grupo   ON equipos (id_grupo);
CREATE INDEX idx_exposicion_equipo ON exposiciones (id_equipo);